python main.py -dataset ENTITY -gpu 0 -without_hier_distill True
python main.py -dataset RELATION -gpu 0 -without_hier_distill True
python main.py -dataset FACT -gpu 0 -without_hier_distill True
python main.py -dataset HYBRID -gpu 0 -without_hier_distill True
python main.py -dataset graph_equal -gpu 0 -without_hier_distill True
python main.py -dataset graph_higher -gpu 0 -without_hier_distill True
python main.py -dataset graph_lower -gpu 0 -without_hier_distill True
python main.py -dataset ENTITY -gpu 1 -without_two_stage True
python main.py -dataset RELATION -gpu 1 -without_two_stage True
python main.py -dataset FACT -gpu 1 -without_two_stage True
python main.py -dataset HYBRID -gpu 1 -without_two_stage True
python main.py -dataset graph_equal -gpu 1 -without_two_stage True
python main.py -dataset graph_lower -gpu 1 -without_two_stage True
python main.py -dataset graph_higher -gpu 1 -without_two_stage True
python main.py -dataset ENTITY -gpu 2 -without_hier_distill True
python main.py -dataset RELATION -gpu 2 -without_hier_distill True
python main.py -dataset FACT -gpu 2 -without_hier_distill True
python main.py -dataset HYBRID -gpu 2 -without_hier_distill True
python main.py -dataset graph_equal -gpu 2 -without_multi_layers True
python main.py -dataset graph_lower -gpu 2 -without_multi_layers True
python main.py -dataset graph_higher -gpu 2 -without_multi_layers True